import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuidv4 } from 'uuid';
import type { AppDefinition, SalesProposal, QualityCheck, DailyRun, FactoryTheme } from './themes.js';
import { THEME_CLUSTERS, getThemeForDay } from './themes.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_ROOT = process.env.FACTORY_OUTPUT || path.join(process.cwd(), 'output');

function formatAppDefinition(app: AppDefinition, index: number): string {
  return `## App ${index + 1}: ${app.appName}

**One-line promise:** ${app.oneLinePromise}

**Target customer:** ${app.targetCustomer}

**Core problem:** ${app.coreProblem}

**What the AI actually does:**
${app.aiDoes.map(b => `- ${b}`).join('\n')}

**Key differentiator vs 2026 alternatives:** ${app.differentiator}

**Primary success metric:** ${app.successMetric}

**Suggested pricing:** ${app.suggestedPricing}

${app.liquidGlassNote ? `**Liquid Glass / interaction note:** ${app.liquidGlassNote}\n` : ''}**Technical notes / integrations needed:** ${app.technicalNotes}
`;
}

function generateSingleProposal(app: AppDefinition): SalesProposal {
  const md = `# Proposal: ${app.appName}

## Subject / Title
**${app.oneLinePromise}**

---

## Opening
Hi [First Name],

If you're like most ${app.targetCustomer.toLowerCase()}, you're dealing with a problem that's costing you real money every month — and the tools you've tried either don't fit your budget or take months to show results.

## Problem Agitation
${app.coreProblem}

Every week this goes unfixed, you're leaving revenue on the table. Your competitors who solve this first will compound their advantage.

## Solution Overview
**${app.appName}** is an AI-powered system built specifically for ${app.targetCustomer.toLowerCase()}. ${app.oneLinePromise}

Unlike enterprise tools that require a dedicated team to configure, ${app.appName} is designed to deliver measurable results within your first 60 days.

## Key Features & Benefits
${app.aiDoes.map(b => `- ✅ ${b}`).join('\n')}

## Expected Outcomes
- **Primary metric:** ${app.successMetric}
- **Differentiator:** ${app.differentiator}
- **Time to value:** Most clients see initial results within 14–30 days

## Pricing & Offer
**${app.suggestedPricing}**

Includes: Full platform access, onboarding setup, 30-day success guarantee, and email support.

## Next Step
Reply to this email with **"DEMO"** and I'll send you a 15-minute walkthrough customized to your situation. No pressure, no long sales call.

## Risk Reversal
If you don't see measurable progress toward ${app.successMetric.split(' within')[0] || app.successMetric} within 60 days, we'll refund your first month. You take zero risk.

---
*Generated by Daily Factory — ${new Date().toISOString().split('T')[0]}*
`;

  return { title: `Proposal: ${app.appName}`, type: 'single', appName: app.appName, markdown: md };
}

function generateSuiteProposal(apps: AppDefinition[], theme: FactoryTheme, clusterName: string): SalesProposal {
  const totalLow = apps.length * 97;
  const totalHigh = apps.length * 247;
  const suitePrice = Math.round(totalLow * 0.65);

  const md = `# Suite Proposal: ${theme} Cluster (${clusterName})

## Subject / Title
**The Complete ${theme} Suite — 5 AI Apps, One Integrated System**

---

## Opening
Hi [First Name],

What if you could solve **five of your biggest ${theme.toLowerCase()} challenges** with one integrated suite — deployed in weeks, not months?

## Problem Agitation
Most ${apps[0].targetCustomer.toLowerCase()} face not one bottleneck but five interconnected ones. Buying point solutions creates tool sprawl, integration headaches, and fragmented data. You need a cluster that works together.

## Solution Overview
The **${theme} Suite** packages five purpose-built AI apps:

${apps.map((a, i) => `### ${i + 1}. ${a.appName}
${a.oneLinePromise}
- **Metric:** ${a.successMetric}
- **Standalone price:** ${a.suggestedPricing}`).join('\n\n')}

## Combined Value
- **5 apps working as one system** — shared data, unified dashboard
- **Cross-app intelligence** — insights from one app improve the others
- **Single onboarding** — live in 2 weeks, not 5 separate implementations

## Expected Outcomes
${apps.map(a => `- ${a.appName}: ${a.successMetric}`).join('\n')}

## Suite Pricing
**$${suitePrice}/mo for the full suite** (save ~35% vs buying individually)

Individual apps available separately if you prefer to start with one.

## Next Step
Reply **"SUITE DEMO"** for a 20-minute walkthrough of how all 5 apps connect to your existing stack.

## Risk Reversal
Start with any single app at standalone pricing. Upgrade to the suite anytime — we'll credit your previous payments toward the bundle.

---
*Generated by Daily Factory — ${new Date().toISOString().split('T')[0]}*
`;

  return { title: `Suite Proposal: ${theme} Cluster`, type: 'suite', markdown: md };
}

function runQualityGate(app: AppDefinition): QualityCheck {
  const hasMetric = /\d+%|\d+x|\d+–\d+|\d+-\d+/.test(app.successMetric);
  const hasPricing = app.suggestedPricing.includes('$');
  const explainable = app.oneLinePromise.length < 120;

  const check: QualityCheck = {
    explainUnder20Sec: explainable,
    measurableOutcome: hasMetric,
    pricingJustified: hasPricing && app.successMetric.length > 10,
    wouldBuy: hasMetric && hasPricing && app.aiDoes.length >= 3,
    languageCurrent: !app.differentiator.toLowerCase().includes('2024') && !app.coreProblem.toLowerCase().includes('covid'),
    passed: false,
  };
  check.passed = check.explainUnder20Sec && check.measurableOutcome && check.pricingJustified && check.wouldBuy && check.languageCurrent;
  return check;
}

function writeFolder(run: DailyRun): string {
  const folderPath = path.join(OUTPUT_ROOT, run.folderPath);
  fs.mkdirSync(path.join(folderPath, '02_Proposals'), { recursive: true });
  fs.mkdirSync(path.join(folderPath, '03_SalesAssets'), { recursive: true });

  const appDefs = run.apps.map((a, i) => formatAppDefinition(a, i)).join('\n---\n\n');
  fs.writeFileSync(path.join(folderPath, '01_AppDefinitions.md'), `# ${run.theme} — App Definitions\n\n**Date:** ${run.date}\n**Cluster:** ${run.clusterName}\n\n---\n\n${appDefs}`);

  for (const proposal of run.proposals) {
    const filename = proposal.type === 'suite'
      ? 'Proposal_Suite.md'
      : `Proposal_${proposal.appName!.replace(/\s+/g, '')}.md`;
    fs.writeFileSync(path.join(folderPath, '02_Proposals', filename), proposal.markdown);
  }

  const cursorNotes = `# Handoff Notes for Cursor

**Date:** ${run.date}
**Theme:** ${run.theme}
**Cluster:** ${run.clusterName}
**Quality gate:** ${run.qualityPassed ? '✅ PASSED' : '⚠️ NEEDS REVIEW'}

## Priority Build Order
${run.apps.map((a, i) => `${i + 1}. **${a.appName}** — ${a.suggestedPricing}\n   - ${a.oneLinePromise}\n   - Integrations: ${a.technicalNotes}`).join('\n\n')}

## Shared Infrastructure
- Auth layer (shared across cluster)
- Dashboard shell with Liquid Glass UI
- Stripe billing integration
- Email notification service

## Dependencies
- Apps 1–3 can scaffold in parallel
- App 4 (Churn/Upsell) depends on usage event pipeline from App 1
- Suite dashboard aggregates all app metrics

## Suggested First Sprint
Build **${run.apps[0].appName}** first — highest standalone sellability.
`;

  fs.writeFileSync(path.join(folderPath, '04_Notes_for_Cursor.md'), cursorNotes);

  const readme = `# ${run.date} — ${run.theme}

Daily Factory output. Drop this folder into Cursor to begin scaffolding.

## Contents
- \`01_AppDefinitions.md\` — 5 refined app definitions
- \`02_Proposals/\` — ${run.proposals.filter(p => p.type === 'single').length} single + 1 suite proposal
- \`03_SalesAssets/\` — (add one-pagers here)
- \`04_Notes_for_Cursor.md\` — engineering handoff
`;
  fs.writeFileSync(path.join(folderPath, 'README.md'), readme);

  return folderPath;
}

// In-memory store (persisted via filesystem)
const runs: DailyRun[] = [];

export function getFactoryRuns(): DailyRun[] {
  return [...runs].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function getFactoryRun(id: string): DailyRun | undefined {
  return runs.find(r => r.id === id);
}

export function generateDailyRun(theme?: FactoryTheme): DailyRun {
  const date = new Date().toISOString().split('T')[0];
  const selectedTheme = theme || getThemeForDay();
  const cluster = THEME_CLUSTERS[selectedTheme];

  const apps: AppDefinition[] = cluster.apps.map(a => ({
    ...a,
    liquidGlassNote: 'Liquid Glass UI — frosted panels, smooth micro-interactions, mobile-first',
  }));

  const proposals: SalesProposal[] = [
    ...apps.map(generateSingleProposal),
    generateSuiteProposal(apps, selectedTheme, cluster.clusterName),
  ];

  const qualityChecks = apps.map(runQualityGate);
  const qualityPassed = qualityChecks.every(q => q.passed);

  const folderPath = `${date}_${cluster.clusterName}`;

  const run: DailyRun = {
    id: uuidv4(),
    date,
    theme: selectedTheme,
    clusterName: cluster.clusterName,
    folderPath,
    apps,
    proposals,
    qualityChecks,
    qualityPassed,
    createdAt: new Date().toISOString(),
  };

  writeFolder(run);
  runs.push(run);
  return run;
}

export { FACTORY_THEMES, getThemeForDay } from './themes.js';
export { OUTPUT_ROOT };
