import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuidv4 } from 'uuid';
import type {
  AppDefinition, SalesProposal, QualityCheck, DailyRun, FactoryTheme, MultiThemeRun, ThemeCluster,
} from './themes.js';
import { THEME_CLUSTERS, getThemeForDay, FACTORY_THEMES } from './themes.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const OUTPUT_ROOT = process.env.FACTORY_OUTPUT || path.join(process.cwd(), 'output');

const GLASS_NOTE = 'Liquid Glass UI — frosted panels, smooth micro-interactions, mobile-first';

function formatAppDefinition(app: AppDefinition, index: number): string {
  return `## App ${index + 1}: ${app.appName}

**One-line promise:** ${app.oneLinePromise}

**Target customer:** ${app.targetCustomer}

**Core problem:** ${app.coreProblem}

**What the AI actually does:**
${app.aiDoes.map(b => `- ${b}`).join('\n')}

**Key differentiator vs 2026 alternatives:** ${app.differentiator}

**Primary success metric:** ${app.successMetric}

**Suggested pricing:** ${app.suggestedPricing}

${app.liquidGlassNote ? `**Liquid Glass / interaction note:** ${app.liquidGlassNote}\n` : ''}**Technical notes / integrations needed:** ${app.technicalNotes}
`;
}

function generateSingleProposal(app: AppDefinition): SalesProposal {
  const md = `# Proposal: ${app.appName}

## Subject / Title
**${app.oneLinePromise}**

---

## Opening
Hi [First Name],

If you're like most ${app.targetCustomer.toLowerCase()}, you're dealing with a problem that's costing you real money every month — and the tools you've tried either don't fit your budget or take months to show results.

## Problem Agitation
${app.coreProblem}

Every week this goes unfixed, you're leaving revenue on the table. Your competitors who solve this first will compound their advantage.

## Solution Overview
**${app.appName}** is an AI-powered system built specifically for ${app.targetCustomer.toLowerCase()}. ${app.oneLinePromise}

Unlike enterprise tools that require a dedicated team to configure, ${app.appName} is designed to deliver measurable results within your first 60 days.

## Key Features & Benefits
${app.aiDoes.map(b => `- ✅ ${b}`).join('\n')}

## Expected Outcomes
- **Primary metric:** ${app.successMetric}
- **Differentiator:** ${app.differentiator}
- **Time to value:** Most clients see initial results within 14–30 days

## Pricing & Offer
**${app.suggestedPricing}**

Includes: Full platform access, onboarding setup, 30-day success guarantee, and email support.

## Next Step
Reply to this email with **"DEMO"** and I'll send you a 15-minute walkthrough customized to your situation. No pressure, no long sales call.

## Risk Reversal
If you don't see measurable progress toward ${app.successMetric.split(' within')[0] || app.successMetric} within 60 days, we'll refund your first month. You take zero risk.

---
*Generated by Daily Factory — ${new Date().toISOString().split('T')[0]}*
`;

  return { title: `Proposal: ${app.appName}`, type: 'single', appName: app.appName, markdown: md };
}

function generateSuiteProposal(
  apps: AppDefinition[],
  theme: FactoryTheme,
  cluster: ThemeCluster,
): SalesProposal {
  const md = `# Suite Proposal: ${cluster.suiteTitle}

## Subject / Title
**${cluster.suiteTitle}**

---

## Opening
Hi [First Name],

${cluster.suitePromise}

## Problem Agitation
Most ${apps[0].targetCustomer.toLowerCase()} face not one bottleneck but five interconnected ones. Buying point solutions creates tool sprawl, integration headaches, and fragmented data. You need an operating system that works together.

## Solution Overview
**${cluster.suiteTitle}** packages five purpose-built AI portals:

${apps.map((a, i) => `### ${i + 1}. ${a.appName}
${a.oneLinePromise}
- **Metric:** ${a.successMetric}
- **Standalone price:** ${a.suggestedPricing}`).join('\n\n')}

**Includes:** ${cluster.suiteIncludes}

## Combined Value
- **5 connected portals + Master Dashboard** — shared identity, event bus, unified analytics
- **Cross-app intelligence** — insights from one portal improve the others
- **Single onboarding** — live in 2 weeks, not 5 separate implementations
- **Liquid Glass design system** — consistent premium UX across all portals

## Expected Outcomes
${apps.map(a => `- **${a.appName}:** ${a.successMetric}`).join('\n')}

## Suite Pricing
**${cluster.suitePricing}**

Individual portals available separately if you prefer to start with one.

## Next Step
${cluster.suiteCta}

## Risk Reversal
Start with any single portal at standalone pricing. Upgrade to the full OS anytime — we'll credit your previous payments toward the bundle.

---
*Theme: ${theme} · Generated by Daily Factory — ${new Date().toISOString().split('T')[0]}*
`;

  return { title: cluster.suiteTitle, type: 'suite', markdown: md };
}

function runQualityGate(app: AppDefinition): QualityCheck {
  const hasMetric = /\d+%|\d+x|\d+–\d+|\d+-\d+|\$\d|higher|faster|more|reduce|reduced|increase|better|safer|improve/i.test(app.successMetric);
  const hasPricing = /\$|credits|\/mo|per-/i.test(app.suggestedPricing);
  const explainable = app.oneLinePromise.length < 140;

  const check: QualityCheck = {
    explainUnder20Sec: explainable,
    measurableOutcome: hasMetric,
    pricingJustified: hasPricing && app.successMetric.length > 5,
    wouldBuy: hasMetric && hasPricing && app.aiDoes.length >= 3,
    languageCurrent: !app.differentiator.toLowerCase().includes('2024') && !app.coreProblem.toLowerCase().includes('covid'),
    passed: false,
  };
  check.passed = check.explainUnder20Sec && check.measurableOutcome && check.pricingJustified && check.wouldBuy && check.languageCurrent;
  return check;
}

function buildRunForTheme(theme: FactoryTheme, date: string): DailyRun {
  const cluster = THEME_CLUSTERS[theme];
  const apps: AppDefinition[] = cluster.apps.map(a => ({ ...a, liquidGlassNote: GLASS_NOTE }));
  const proposals: SalesProposal[] = [
    ...apps.map(generateSingleProposal),
    generateSuiteProposal(apps, theme, cluster),
  ];
  const qualityChecks = apps.map(runQualityGate);

  return {
    id: uuidv4(),
    date,
    theme,
    clusterName: cluster.clusterName,
    folderPath: cluster.folderSlug,
    apps,
    proposals,
    qualityChecks,
    qualityPassed: qualityChecks.every(q => q.passed),
    createdAt: new Date().toISOString(),
  };
}

function writeThemeSubfolder(basePath: string, run: DailyRun, cluster: ThemeCluster): void {
  const themePath = path.join(basePath, cluster.folderSlug);
  const proposalsPath = path.join(themePath, 'Proposals');
  fs.mkdirSync(proposalsPath, { recursive: true });

  const appDefs = run.apps.map((a, i) => formatAppDefinition(a, i)).join('\n---\n\n');
  fs.writeFileSync(
    path.join(themePath, 'Apps.md'),
    `# ${run.theme} — Refined Apps\n\n**Date:** ${run.date}\n**Cluster:** ${run.clusterName}\n\n---\n\n${appDefs}`,
  );

  for (const proposal of run.proposals) {
    if (proposal.type === 'suite') {
      fs.writeFileSync(path.join(themePath, 'Suite_Proposal.md'), proposal.markdown);
    } else {
      const filename = `Proposal_${proposal.appName!.replace(/[\s-]+/g, '')}.md`;
      fs.writeFileSync(path.join(proposalsPath, filename), proposal.markdown);
    }
  }
}

function writeSingleThemeFolder(run: DailyRun): string {
  const cluster = THEME_CLUSTERS[run.theme];
  const folderPath = path.join(OUTPUT_ROOT, run.folderPath);
  fs.mkdirSync(path.join(folderPath, '02_Proposals'), { recursive: true });
  fs.mkdirSync(path.join(folderPath, '03_SalesAssets'), { recursive: true });

  const appDefs = run.apps.map((a, i) => formatAppDefinition(a, i)).join('\n---\n\n');
  fs.writeFileSync(
    path.join(folderPath, '01_AppDefinitions.md'),
    `# ${run.theme} — App Definitions\n\n**Date:** ${run.date}\n**Cluster:** ${run.clusterName}\n\n---\n\n${appDefs}`,
  );

  for (const proposal of run.proposals) {
    const filename = proposal.type === 'suite'
      ? 'Proposal_Suite.md'
      : `Proposal_${proposal.appName!.replace(/[\s-]+/g, '')}.md`;
    fs.writeFileSync(path.join(folderPath, '02_Proposals', filename), proposal.markdown);
  }

  fs.writeFileSync(path.join(folderPath, '04_Notes_for_Cursor.md'), buildCursorNotes(run));
  fs.writeFileSync(path.join(folderPath, 'README.md'), `# ${run.date} — ${run.theme}\n\nDaily Factory output for Cursor.\n`);
  return folderPath;
}

function buildMasterNotes(runs: DailyRun[]): string {
  return `# Master Notes for Cursor

**Date:** ${runs[0]?.date ?? new Date().toISOString().split('T')[0]}
**Themes in this package:** ${runs.map(r => r.theme).join(' · ')}
**Total apps:** ${runs.reduce((s, r) => s + r.apps.length, 0)}
**Total proposals:** ${runs.reduce((s, r) => s + r.proposals.length, 0)}

---

## Build Priority

1. **Conversion & Revenue cluster first** — highest near-term revenue potential
2. Start with **Offer-Optics AI** and **Profit-Pulse AI** — clearest immediate ROI stories for early sales
3. Shared event bus and identity layer — design once, reuse across all 15 apps

---

## Shared Infrastructure (build once)

- **Identity layer** — auth, orgs, roles across all portals
- **Event bus** — cross-app signals (e.g. Offer-Optics price change → Bridge-Builder demo update)
- **Liquid Glass design system** — frosted panels, Glass Slider, Glass Shredder, gift-box assets
- **Master Dashboard** — aggregates metrics from all connected portals
- **Stripe billing** — per-portal and suite-tier subscriptions

---

## Privacy & Compliance (mandatory)

- **Closer-Command AI** — explicit consent before call recording; configurable retention
- **Profit-Pulse / bank connections** — read-only access, encrypted tokens, user revoke anytime
- **CRM integrations** — OAuth scopes minimum necessary

---

## Theme Summaries

${runs.map(r => {
  const cluster = THEME_CLUSTERS[r.theme];
  return `### ${r.theme}
- **Suite:** ${cluster.suiteTitle} (${cluster.suitePricing})
- **Apps:** ${r.apps.map(a => a.appName).join(', ')}
- **First build:** ${r.apps[0].appName}`;
}).join('\n\n')}

---

## Quality Gate Summary

${runs.map(r => `- **${r.theme}:** ${r.qualityChecks.filter(q => q.passed).length}/${r.qualityChecks.length} apps passed ${r.qualityPassed ? '✅' : '⚠️'}`).join('\n')}

---

*Send this entire folder to Cursor to begin scaffolding.*
`;
}

function buildCursorNotes(run: DailyRun): string {
  return `# Handoff Notes for Cursor

**Date:** ${run.date}
**Theme:** ${run.theme}
**Cluster:** ${run.clusterName}
**Quality gate:** ${run.qualityPassed ? '✅ PASSED' : '⚠️ NEEDS REVIEW'}

## Priority Build Order
${run.apps.map((a, i) => `${i + 1}. **${a.appName}** — ${a.suggestedPricing}\n   - ${a.oneLinePromise}\n   - Integrations: ${a.technicalNotes}`).join('\n\n')}

## Shared Infrastructure
- Auth layer (shared across cluster)
- Dashboard shell with Liquid Glass UI
- Stripe billing integration
- Email notification service

## Suggested First Sprint
Build **${run.apps[0].appName}** first — highest standalone sellability.
`;
}

const runs: DailyRun[] = [];
const multiRuns: MultiThemeRun[] = [];

export function getFactoryRuns(): DailyRun[] {
  return [...runs].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function getFactoryRun(id: string): DailyRun | undefined {
  return runs.find(r => r.id === id);
}

export function getMultiThemeRuns(): MultiThemeRun[] {
  return [...multiRuns].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function getMultiThemeRun(id: string): MultiThemeRun | undefined {
  return multiRuns.find(r => r.id === id);
}

export function generateDailyRun(theme?: FactoryTheme): DailyRun {
  const date = new Date().toISOString().split('T')[0];
  const selectedTheme = theme || getThemeForDay();
  const cluster = THEME_CLUSTERS[selectedTheme];

  const run = buildRunForTheme(selectedTheme, date);
  run.folderPath = `${date}_${cluster.clusterName}`;
  writeSingleThemeFolder(run);
  runs.push(run);
  return run;
}

export function generateMultiThemeRun(
  themes: FactoryTheme[],
  folderSuffix = 'Three_Themes',
): MultiThemeRun {
  const date = new Date().toISOString().split('T')[0];
  const folderPath = `${date}_${folderSuffix}`;
  const basePath = path.join(OUTPUT_ROOT, folderPath);
  fs.mkdirSync(basePath, { recursive: true });

  const themeRuns = themes.map(t => buildRunForTheme(t, date));
  for (const run of themeRuns) {
    writeThemeSubfolder(basePath, run, THEME_CLUSTERS[run.theme]);
    runs.push(run);
  }

  const masterNotes = buildMasterNotes(themeRuns);
  fs.writeFileSync(path.join(basePath, 'Master_Notes_for_Cursor.md'), masterNotes);

  fs.writeFileSync(
    path.join(basePath, 'README.md'),
    `# Daily Factory — ${date} Multi-Theme Run

${themes.length} themes · ${themeRuns.reduce((s, r) => s + r.apps.length, 0)} apps · ${themeRuns.reduce((s, r) => s + r.proposals.length, 0)} proposals

## Contents
${themes.map(t => `- \`${THEME_CLUSTERS[t].folderSlug}/\` — ${t}`).join('\n')}
- \`Master_Notes_for_Cursor.md\` — build priority and shared infrastructure

Drop this folder into Cursor to begin scaffolding.
`,
  );

  const multi: MultiThemeRun = {
    id: uuidv4(),
    date,
    folderPath,
    themes: themeRuns,
    masterNotes,
    totalApps: themeRuns.reduce((s, r) => s + r.apps.length, 0),
    totalProposals: themeRuns.reduce((s, r) => s + r.proposals.length, 0),
    qualityPassed: themeRuns.every(r => r.qualityPassed),
    createdAt: new Date().toISOString(),
  };

  multiRuns.push(multi);
  return multi;
}

/** Generate the standard first-three-theme package for Cursor */
export function generateThreeThemePackage(): MultiThemeRun {
  return generateMultiThemeRun([
    'Conversion & Revenue',
    'Margin & Operations',
    'Acquisition & Lead Systems',
  ]);
}

export { FACTORY_THEMES, getThemeForDay } from './themes.js';
